# Generated by Django 5.0.3 on 2024-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('nombreUsuario', models.CharField(max_length=60, verbose_name='usuario')),
                ('email', models.CharField(max_length=60, verbose_name='email')),
                ('password', models.CharField(max_length=60, verbose_name='contraseña')),
            ],
        ),
    ]
