# Generated by Django 5.0.3 on 2024-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='titulo')),
                ('origen', models.CharField(max_length=60, verbose_name='origen')),
                ('chapters', models.CharField(max_length=60, verbose_name='capitulos')),
                ('estreno', models.CharField(max_length=60, verbose_name='estreno')),
            ],
        ),
    ]
